### ISSUE TITLE
NBVIEWER of 

### ISSUE THREAD

**Issue by peisenha** [softEcon/course#2]
Dear Yike, 

I hope all is well! Could you please figure out why the Job Search notebook cannot be viewed in the nbviewer. Please make sure that the link to your lecture works in the README file. 

Please let me know if you have any questions or run into problems. 

Best, Philipp

**Comment by Yike** [comment]
Dear Philipp,

I hope all is well too! I just wonder why you don't think it works. Can we talk about it briefly after the TA session? Thanks!

Best, Yike

**Comment by peisenha** [comment]
Dear Yike,

Sure, let's talk later...

Best, Philipp

On Fri, May 1, 2015 at 1:01 PM, Yike <notifications@github.com> wrote:

> Dear Philipp,
>
> I hope all is well too! I just wonder why you don't think it works. Can we
> talk about it briefly after the TA session? Thanks!
>
> Best, Yike
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/softEcon/course/issues/2#issuecomment-98188783>.
>



-- 
*Philipp Eisenhauer*
Economist

Mail eisenhauer@policy-lab.org
Web www.policy-lab.org/peisenha
Repository https://github.com/peisenha

**Comment by peisenha** [comment]
Thanks, all works fine now.
